config/routes.rb
Rails.application.routes.draw do
  root 'quotes#index'
  resources :quotes, except: [:destroy] do
    resources :comments, except: [:show, :destroy, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include AuthorChanger

  before_save :change_author
  validates :content, presence: true, length: { minimum: 10, maximum: 400 }
  belongs_to :quote
end

app/models/concerns/author_changer.rb
module AuthorChanger
  def change_author
    if self.author.blank?
      self.author = "Anonym"
    end
  end
end

app/models/quote.rb
class Quote < ApplicationRecord
  include AuthorChanger

  before_save :change_author
  validates :content, presence: true, length: { minimum: 10, maximum: 400 }
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_quote, only: [:new, :create]

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.quote = @quote

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @quote, notice: 'Your comment has been saved.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :author)
    end

    def set_quote
      @quote = Quote.find(params[:quote_id])
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update]

  # GET /quotes
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  def show
    @comments = @quote.comments
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to root_url, notice: 'Quote was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /quotes/1
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:content, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
  def remove_quote_mark(str)
    str.chomp('"').chomp('\'').chomp('').chomp('”').chomp('“').
        reverse.chomp('"').chomp('\'').chomp('').chomp('”').chomp('“')
        .reverse
  end

  def add_whitespace_to_long_string(str)
    str.split(/\s/).map do |word|
        word.gsub(/(.{15})/, '\1 ')
    end.join(" ")
  end
end

app/views/application/_error.html.erb
<% if passed_model.errors.full_messages_for(symbol).any? %>
  <div id="error_explanation">
    <% passed_model.errors.full_messages_for(symbol).each do |symbol| %>
      <%= symbol %>
    <% end %>
  </div>
<% end %>

app/views/application/_form.html.erb
<%= form_with(model: passed_model, local: true, url: url) do |form| %>
  <div class="actions">

    <div class="row">
      <div class="col-sm-12 col-centered">
        <%= form.label passed_model.class.name %>
        <%= render 'error', passed_model: passed_model, symbol: :content %>
        <%= form.text_area :content, rows: rows_number, class: 'form-control' %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12 col-centered">
        <%= form.label :author %>
        <%= render 'error', passed_model: passed_model, symbol: :author %>
        <%= form.text_field :author, class: 'form-control' %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-4 col-centered">
        <%= form.submit action + " " + passed_model.class.name, class: 'btn btn-success' %>
      </div>
    </div>

  </div>
<% end %>

app/views/application/_header.html.erb
<header>
  <div class="row">
    <div class="col-sm-12 title">
      Quotes
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-centered">
      <p id="notice"><%= notice %></p>
    </div>
  </div>
</header>

app/views/comments/new.html.erb
<%= render 'form', passed_model: @comment, action: 'Add', url: quote_comments_url, rows_number: "8" %>

<div class="row">
  <div class="col-sm-4 col-centered">
    <%= button_to 'Back', @quote, method: :get, class: 'btn btn-success'%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quotes for Netguru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render 'header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/quotes/_comment.html.erb
<section>
  <% comments.each do |comment| %>
    <article>
      <div class="row">
        <div class="col-sm-3 col-centered">
          <div class="dialogbox">
            <span class="comment-author">
              <%= add_whitespace_to_long_string comment.author %>
            </span>
            <div class="body">
              <span class="tip tip-up"></span>
              <div class="message">
                <span>
                  <%= add_whitespace_to_long_string comment.content %>
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </article>
  <% end %>
</section>

app/views/quotes/_quote.html.erb
<article>
  <div class="quote">
    <%= remove_quote_mark add_whitespace_to_long_string quote.content %>
    <span class="author">
          <%= add_whitespace_to_long_string quote.author %>
    </span>
  </div>
</article>

app/views/quotes/edit.html.erb
<%= render 'form', passed_model: @quote, action: 'Edit', url: quote_path, rows_number: "10" %>

<div class="row">
  <div class="col-sm-4 col-centered">
    <%= button_to 'Back', root_path, method: :get, class: 'btn btn-success' %>
  </div>
</div>

app/views/quotes/index.html.erb
<section id="quotes">
  <div class="row">
  <% @quotes.each do |quote| %>
    <div class="col-sm-4">
      <%= link_to quote do %>
        <%= render 'quote', quote: quote %>
      <% end %>
    </div>
  <% end %>
  </div>
</section>

<div class="row">
  <div class="col-sm-2 col-centered">
    <%= button_to 'Add Quote',  new_quote_path, method: :get, class: "btn btn-success btn-lg" %>
  </div>
</div>

app/views/quotes/new.html.erb
<%= render 'form', passed_model: @quote, action: 'Add', url: quotes_path, rows_number: "10"  %>

<div class="row">
  <div class="col-sm-4 col-centered">
    <%= button_to 'Back', root_path, method: :get, class: 'btn btn-success' %>
  </div>
</div>

app/views/quotes/show.html.erb
<div class="row">
  <div class="col-sm-8 col-centered">
    <%= render 'quote', quote: @quote %>
  </div>
</div>

<%= render 'comment', comments: @comments %>


<div class="row">
  <div class="col-sm-4 col-centered">
    <%= button_to 'Add comment', new_quote_comment_path(@quote), method: :get, class: 'btn btn-success' %>
  </div>
</div>
<div class="row">
  <div class="col-sm-4 col-centered">
    <%= button_to 'Edit quote', edit_quote_path(@quote), method: :get, class: 'btn btn-success' %>
  </div>
</div>
<div class="row">
  <div class="col-sm-4 col-centered">
    <%= button_to 'Back', root_path, method: :get, class: 'btn btn-success' %>
  </div>
</div>